In [10]:
import pandas as pd
import numpy as np

# On crée 10 lignes de données réalistes
data_test = {
    'numero_dpe': ['DPE001', 'DPE001', 'DPE003', 'DPE004', 'DPE005', 'DPE006', 'DPE007', 'DPE008', 'DPE009', 'DPE010'],
    'numero_rpls_logement': [np.nan, 'RPLS-99', np.nan, np.nan, 'RPLS-88', np.nan, np.nan, np.nan, 'RPLS-77', np.nan],
    'numero_immatriculation_copropriete': ['COPRO-1', np.nan, 'COPRO-2', np.nan, np.nan, 'COPRO-3', np.nan, 'COPRO-4', np.nan, np.nan],
    'adresse_brut': ['10 rue de Rivoli', '5 av Foch', '12 rue de la Paix', '3 bld Haussmann', '20 rue de Bercy', '8 rue du Bac', '1 av de Lyon', '90 rue de Paris', '45 rue du Commerce', '7 rue de Rennes'],
    'code_postal_brut': [75001, 75016, 75001, 75008, 75012, 75007, 69000, 75012, 75015, 75006],
    'date_etablissement_dpe': ['2023-01-10', '2022-05-15', '2023-08-20', '2021-12-01', '2023-03-12', '2022-11-30', '2023-01-05', '2023-06-25', '2022-09-10', '2023-02-28'],
    'date_fin_validite_dpe': ['2033-01-10', '2032-05-15', '2033-08-20', '2031-12-01', '2033-03-12', '2032-11-30', '2033-01-05', '2033-06-25', '2032-09-10', '2033-02-28'],
    'annee_construction': [1950, 1970, 1900, 1985, 2010, 1960, 1975, 1955, 2015, 1930],
    'etiquette_dpe': ['G', 'C', 'A', 'E', 'B', 'D', 'F', 'G', 'A', 'E'],
    'etiquette_ges': ['F', 'B', 'A', 'D', 'B', 'C', 'E', 'F', 'A', 'D'],
    'surface_habitable_logement': [45.5, 120.0, 32.0, 85.0, 65.0, 50.0, 75.0, 42.0, 95.0, 28.0],
    'conso_5_usages_par_m2_ef': [450.2, 120.5, 45.0, 280.0, 85.0, 210.0, 360.0, 480.0, 40.0, 310.0],
    'cout_total_5_usages': [2500, 1500, 400, 2000, 800, 1200, 1900, 2800, 500, 1100],
    'qualite_isolation_murs': ['insuffisante', 'bonne', 'très bonne', 'moyenne', 'très bonne', 'moyenne', 'insuffisante', 'insuffisante', 'très bonne', 'moyenne'],
    'qualite_isolation_menuiseries': ['moyenne', 'bonne', 'très bonne', 'moyenne', 'bonne', 'moyenne', 'insuffisante', 'moyenne', 'très bonne', 'insuffisante'],
    'type_ventilation': ['Naturelle', 'VMC simple', 'VMC double', 'VMC simple', 'VMC double', 'Naturelle', 'Naturelle', 'VMC simple', 'VMC double', 'Naturelle'],
    'type_energie_principale_chauffage': ['Fioul', 'Gaz', 'Électricité', 'Gaz', 'Électricité', 'Gaz', 'Fioul', 'Électricité', 'Électricité', 'Gaz'],
    'besoin_chauffage': [15000, 8000, 2000, 10000, 3500, 7000, 12000, 14000, 2500, 6000],
    'besoin_ecs': [2500, 3000, 1500, 2800, 2000, 2200, 2600, 2400, 1800, 1600],
    'type_batiment': ['appartement', 'maison', 'appartement', 'appartement', 'appartement', 'appartement', 'maison', 'appartement', 'appartement', 'appartement'],
    'nombre_appartement': [12, 1, 8, 20, 50, 15, 1, 10, 40, 6]
}

df_source = pd.DataFrame(data_test)
# Sauvegarde en CSV pour simuler le fichier réel
df_source.to_csv('big_dpe_simulated.csv', index=False)
print("✅ Fichier 'big_dpe_simulated.csv' créé pour le test !")
df_source=pd.read_csv("./data_light_output/new_dpe03existant_paris_light.csv", low_memory=False)
df_source.head()

✅ Fichier 'big_dpe_simulated.csv' créé pour le test !

,numero_dpe,date_etablissement_dpe,date_fin_validite_dpe,numero_rpls_logement,numero_immatriculation_copropriete,etiquette_dpe,etiquette_ges,type_batiment,annee_construction,nombre_appartement,...,besoin_ecs,conso_5_usages_par_m2_ep,cout_total_5_usages,type_energie_principale_chauffage,type_ventilation,arrondissement,logement,statut_juridique,is_renovated,annee
0,2675E0081184O,2026-01-12,2036-01-11,NaN,NaN,F,C,appartement,NaN,1.0,...,1126.0,408.0,2172.3,Électricité,NaN,4,1,Privé (Individuel),0,2026
1,2675E0079556Y,2026-01-12,2036-01-11,NaN,NaN,D,D,appartement,NaN,1.0,...,1000.3,230.0,803.4,Réseau de Chauffage urbain,NaN,11,1,Privé (Individuel),1,2026
2,2675E0082260Y,2026-01-12,2036-01-11,NaN,NaN,F,C,appartement,NaN,1.0,...,872.7,387.0,1237.6,Électricité,NaN,15,1,Privé (Individuel),0,2026
3,2675E0081107P,2026-01-12,2036-01-11,NaN,NaN,F,C,appartement,1975.0,1.0,...,664.1,542.0,761.6,Électricité,NaN,17,1,Privé (Individuel),0,2026
4,2675E0077739B,2026-01-12,2036-01-11,NaN,NaN,E,E,appartement,1880.0,NaN,...,1270.0,238.1,1773.0,Gaz naturel,NaN,9,1,Privé (Individuel),0,2026

In [12]:
df_light=df_source.copy()
df_light['statut_juridique'] = 'Privé (Individuel)'
df_light["statut_juridique"]

0         Privé (Individuel)
1         Privé (Individuel)
2         Privé (Individuel)
3         Privé (Individuel)
4         Privé (Individuel)
                 ...
746740    Privé (Individuel)
746741    Privé (Individuel)
746742    Privé (Individuel)
746743    Privé (Individuel)
746744    Privé (Individuel)
Name: statut_juridique, Length: 746745, dtype: object

In [4]:
# df_light["etiquette_dpe"] = df_light["etiquette_dpe"].astype("category")

condition_sociale = df_light["numero_rpls_logement"].notna()
condition_privet_copro = df_light["numero_immatriculation_copropriete"].notna()

df_light.loc[condition_sociale, "statut_juridique"] = "Social"
df_light.loc[condition_privet_copro, "statut_juridique"] = "Privé (Copro)"
df_light["is_renovated"] = (
    df_light["etiquette_dpe"].isin(["A", "B", "C", "D"]).astype(int)
)
conditions_series=df_light['code_postal_brut'].astype(str).str.startswith('75')
df_light=df_light[conditions_series]
df_light['adresse_brut']

0               88 RUE SAINT-LOUIS EN L'ILE
1                     82 RUE DE LA ROQUETTE
2                     93, Rue Saint Charles
3                        12 avenue de Versy
4         38 rue Marguerite de Rochechouart
                        ...
750224                     52 rue d'Auteuil
750225                   8 RUE JEAN MARIDOR
750226                       21 rue Duperré
750227              74 RUE DE L'ABBE GROULT
750228                du Faubourg du Temple
Name: adresse_brut, Length: 746956, dtype: object

In [19]:
# 1. Convertir en format datetime
df_light['date_etablissement_dpe'] = pd.to_datetime(df_light['date_etablissement_dpe'])

# 2. Vérifier que c'est bien du datetime
print(df_light['date_etablissement_dpe'].dtype)  # Doit afficher: datetime64[ns]

# 3. Créer la colonne année
df_light['année'] = df_light['date_etablissement_dpe'].dt.year

df_light['année']

datetime64[ns]

0         2026
1         2026
2         2026
3         2026
4         2026
          ...
746740    2021
746741    2021
746742    2021
746743    2021
746744    2021
Name: année, Length: 746745, dtype: int32

In [22]:
 
 # 1. On calcule la moyenne par CP et Statut
renovation_by_postal_and_status = df_light.groupby(
    ['année', 'statut_juridique']
)


renovation_by_postal_and_status_df=renovation_by_postal_and_status['is_renovated'].mean()*100
renovation_by_postal_and_status_df

année  statut_juridique
2021   Privé (Individuel)    39.233852
2022   Privé (Individuel)    45.000496
2023   Privé (Individuel)    48.691251
2024   Privé (Individuel)    55.642473
2025   Privé (Individuel)    48.256287
2026   Privé (Individuel)    47.201450
Name: is_renovated, dtype: float64

In [40]:
# 2. Grouper et compter
result_df = (
    df_light.groupby(["annee", "arrondissement", "statut_juridique"])
    .agg({"is_renovated": ["count", "mean"], "logement": ["count"]})
    .reset_index()
)
# 3. Renommer les colonnes
# result_df.columns = ['annee', 'arrondissement','total_logements_renove' , 'pourcentage_renove','total_logements']
# result_df['pourcentage_renove'] = (result_df['pourcentage_renove'] * 100).round(2)
result_df
df_light[
    ["annee", "arrondissement", "statut_juridique", "logement", "is_renovated"]
].groupby(["annee", "arrondissement", "statut_juridique"]).agg(
    {"is_renovated": ["count", "mean"], "logement": ["count"]}
)

                                        is_renovated           logement
                                               count      mean    count
annee arrondissement statut_juridique
2021  1              Privé (Individuel)          289  0.387543      289
      2              Privé (Individuel)          400  0.472500      400
      3              Privé (Individuel)          548  0.459854      548
      4              Privé (Individuel)          618  0.564725      618
      5              Privé (Individuel)          830  0.368675      830
...                                              ...       ...      ...
2026  16             Privé (Individuel)          256  0.460938      256
      17             Privé (Individuel)          314  0.487261      314
      18             Privé (Individuel)          300  0.463333      300
      19             Privé (Individuel)          164  0.664634      164
      20             Privé (Individuel)          173  0.485549      173

[120 rows x 3 columns]

In [42]:
# Groupement initial pour obtenir les totaux par statut
grouped_data = df_light.groupby(['annee', 'arrondissement', 'statut_juridique']).agg(
    count_total_par_statut=('logement', 'count'), # Nombre total de logements pour ce statut
    count_renove_par_statut=('is_renovated', 'sum')  # Nombre de logements rénovés pour ce statut
).reset_index()

print("\n--- Étape 1 : Agrégation par Année, Arrondissement, Statut ---")
print(grouped_data)

--- Étape 1 : Agrégation par Année, Arrondissement, Statut ---
     annee  arrondissement    statut_juridique  count_total_par_statut  \
0     2021               1  Privé (Individuel)                     289
1     2021               2  Privé (Individuel)                     400
2     2021               3  Privé (Individuel)                     548
3     2021               4  Privé (Individuel)                     618
4     2021               5  Privé (Individuel)                     830
..     ...             ...                 ...                     ...
115   2026              16  Privé (Individuel)                     256
116   2026              17  Privé (Individuel)                     314
117   2026              18  Privé (Individuel)                     300
118   2026              19  Privé (Individuel)                     164
119   2026              20  Privé (Individuel)                     173

     count_renove_par_statut
0                        112
1                        189
2                        252
3                        349
4                        306
..                       ...
115                      118
116                      153
117                      139
118                      109
119                       84

[120 rows x 5 columns]

In [46]:
grouped = df_light.groupby(['annee', 'arrondissement', 'statut_juridique'])['is_renovated'].agg(['count', 'sum'])
grouped
unstacked = grouped.unstack(fill_value=0)
unstacked

                                  count                sum
statut_juridique     Privé (Individuel) Privé (Individuel)
annee arrondissement
2021  1                             289                112
      2                             400                189
      3                             548                252
      4                             618                349
      5                             830                306
...                                 ...                ...
2026  16                            256                118
      17                            314                153
      18                            300                139
      19                            164                109
      20                            173                 84

[120 rows x 2 columns]

In [16]:
# 1. Convertir en string et remplir les zéros manquants

# condition= df_light['code_postal_brut'].astype(str).str.startswith("75")

# df_light=df_light[condition]
# df_light['code_postal_clean'] = df_light['code_postal_brut'].astype(str).str.zfill(5)
# df_light['arrondissement'] = df_light['code_postal_clean'].str[-2:].astype(int)
# # 3. Filtrer pour garder uniquement les arrondissements 1-20
# df_light = df_light[df_light['arrondissement'].between(1, 20)]
# df_light['arrondissement']
# df_light["total"]=df_light['numero_dpe'].notna().astype(int)
# df_light["total"]

In [53]:
# Groupement initial pour obtenir les totaux par statut
grouped_data = df_light.groupby(['annee', 'arrondissement', 'statut_juridique']).agg(
    total_logements=('logement', 'count'),          # Nombre total de logements pour ce statut
    total_logements_renove=('is_renovated', 'sum'), # Nombre de logements rénovés pour ce statut (virgule ajoutée ici)
    pourcentage_renove=('is_renovated', 'mean')      # Pourcentage de rénovés pour ce statut
).reset_index()
grouped_data['pourcentage_renove'] = (grouped_data['pourcentage_renove'] * 100).round(1)

print(grouped_data)

     annee  arrondissement    statut_juridique  total_logements  \
0     2021               1  Privé (Individuel)              289
1     2021               2  Privé (Individuel)              400
2     2021               3  Privé (Individuel)              548
3     2021               4  Privé (Individuel)              618
4     2021               5  Privé (Individuel)              830
..     ...             ...                 ...              ...
115   2026              16  Privé (Individuel)              256
116   2026              17  Privé (Individuel)              314
117   2026              18  Privé (Individuel)              300
118   2026              19  Privé (Individuel)              164
119   2026              20  Privé (Individuel)              173

     total_logements_renove  pourcentage_renove
0                       112                38.8
1                       189                47.2
2                       252                46.0
3                       349                56.5
4                       306                36.9
..                      ...                 ...
115                     118                46.1
116                     153                48.7
117                     139                46.3
118                     109                66.5
119                      84                48.6

[120 rows x 6 columns]

In [59]:
pivot_df = grouped_data.pivot(
    index=['annee', 'arrondissement'],      # Les clés qui restent en lignes
    columns='statut_juridique',              # La colonne qu'on veut transformer en colonnes
    values=['total_logements', 'total_logements_renove', 'pourcentage_renove']  # Les colonnes à pivoter
).reset_index()

pivot_df.columns
# Après pivot(), les noms de colonnes deviennent complexes (multi-niveaux)
# On les aplatit pour avoir des noms simples
pivot_df.columns = [f'{col[0]}_{col[1]}'.lower() if col[1] else col[0] 
                    for col in pivot_df.columns.values]


print(pivot_df)
pivot_df.columns

     annee  arrondissement  total_logements_privé (individuel)  \
0     2021               1                               289.0
1     2021               2                               400.0
2     2021               3                               548.0
3     2021               4                               618.0
4     2021               5                               830.0
..     ...             ...                                 ...
115   2026              16                               256.0
116   2026              17                               314.0
117   2026              18                               300.0
118   2026              19                               164.0
119   2026              20                               173.0

     total_logements_renove_privé (individuel)  \
0                                        112.0
1                                        189.0
2                                        252.0
3                                        349.0
4                                        306.0
..                                         ...
115                                      118.0
116                                      153.0
117                                      139.0
118                                      109.0
119                                       84.0

     pourcentage_renove_privé (individuel)
0                                     38.8
1                                     47.2
2                                     46.0
3                                     56.5
4                                     36.9
..                                     ...
115                                   46.1
116                                   48.7
117                                   46.3
118                                   66.5
119                                   48.6

[120 rows x 5 columns]

Index(['annee', 'arrondissement', 'total_logements_privé (individuel)',
       'total_logements_renove_privé (individuel)',
       'pourcentage_renove_privé (individuel)'],
      dtype='object')

In [63]:
# 1. On pivote
pivot_df = grouped_data.pivot(
    index=['annee', 'arrondissement'],      
    columns='statut_juridique',              
    values=['total_logements', 'total_logements_renove', 'pourcentage_renove']
).reset_index()

# 2. On aplatit les noms des colonnes
pivot_df.columns = [f'{col[0]}_{col[1]}'.lower() if col[1] else col[0] 
                    for col in pivot_df.columns.values]

# --- ASTUCE POUR ÉVITER L'ERREUR ---
# On affiche les colonnes générées pour être SÛR du nom exact
print("Colonnes générées par le pivot :", pivot_df.columns.tolist())

# On définit un dictionnaire de renommage flexible
# Vérifiez bien si c'est 'social' ou 'social (collectif)' ou autre dans votre print ci-dessus
mapping = {
    'total_logements_privé (individuel)': 'logements_prives',
    'total_logements_social': 'logements_sociaux',
    'total_logements_renove_privé (individuel)': 'logements_prives_renoves',
    'total_logements_renove_social': 'logements_sociaux_renoves',
    'pourcentage_renove_privé (individuel)': 'pourcentage_prives_renoves',
    'pourcentage_renove_social': 'pourcentage_sociaux_renoves'
}

# On renomme seulement les colonnes qui existent réellement dans pivot_df
pivot_df = pivot_df.rename(columns=mapping)

# Si une colonne manque (ex: pas de social), on la crée avec des 0 pour éviter que le calcul plante
for col in ['logements_prives', 'logements_sociaux', 'logements_prives_renoves', 'logements_sociaux_renoves']:
    if col not in pivot_df.columns:
        pivot_df[col] = 0

# 4. On remplace les cases vides (NaN) par 0
pivot_df = pivot_df.fillna(0)

# 5. Maintenant le calcul ne plantera plus !
pivot_df['total_logements'] = pivot_df['logements_prives'] + pivot_df['logements_sociaux']
pivot_df['total_logements_renoves'] = pivot_df['logements_prives_renoves'] + pivot_df['logements_sociaux_renoves']

# Pourcentage global (privé + social)
pivot_df['pourcentage_total_renove'] = 0
mask = pivot_df['total_logements'] > 0
pivot_df.loc[mask, 'pourcentage_total_renove'] = ((pivot_df['total_logements_renoves'] / pivot_df['total_logements']) * 100).round(1)

print("\n--- Tableau final réussi ---")
print(pivot_df.head())

Colonnes générées par le pivot : ['annee', 'arrondissement', 'total_logements_privé (individuel)', 'total_logements_renove_privé (individuel)', 'pourcentage_renove_privé (individuel)']

--- Tableau final réussi ---
   annee  arrondissement  logements_prives  logements_prives_renoves  \
0   2021               1             289.0                     112.0
1   2021               2             400.0                     189.0
2   2021               3             548.0                     252.0
3   2021               4             618.0                     349.0
4   2021               5             830.0                     306.0

   pourcentage_prives_renoves  logements_sociaux  logements_sociaux_renoves  \
0                        38.8                  0                          0
1                        47.2                  0                          0
2                        46.0                  0                          0
3                        56.5                  0                          0
4                        36.9                  0                          0

   total_logements  total_logements_renoves  pourcentage_total_renove
0            289.0                    112.0                      38.8
1            400.0                    189.0                      47.2
2            548.0                    252.0                      46.0
3            618.0                    349.0                      56.5
4            830.0                    306.0                      36.9

C:\Users\ntpar\AppData\Local\Temp\ipykernel_23660\3760009615.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[38.8 47.2 46.  56.5 36.9 34.4 38.8 36.9 43.7 40.9 38.5 39.  43.8 33.6
 34.6 34.9 36.9 40.3 50.3 37.1 47.9 53.7 48.9 43.5 37.2 44.1 42.4 44.7
 42.3 47.9 46.5 48.  48.7 39.5 43.3 44.7 40.5 40.3 56.9 48.4 36.4 44.7
 35.7 36.1 35.8 41.3 40.8 38.6 39.1 45.8 42.6 45.  62.4 50.3 54.7 37.4
 36.3 46.9 68.2 58.5 46.6 43.8 41.2 42.  35.1 34.1 39.5 38.2 39.6 56.7
 55.6 65.6 66.3 59.8 50.8 32.4 49.3 50.9 75.4 66.8 39.1 35.8 39.4 37.2
 30.6 34.1 35.8 40.5 34.7 33.  36.1 51.4 61.3 52.9 54.9 37.9 37.  45.6
 64.  58.  31.4 60.  34.9 40.3 78.2 41.6 44.7 62.3 41.8 36.6 55.5 41.2
 27.8 47.3 55.6 46.1 48.7 46.3 66.5 48.6]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pivot_df.loc[mask, 'pourcentage_total_renove'] = ((pivot_df['total_logements_renoves'] / pivot_df['total_logements']) * 100).round(1)

In [ ]:
# --- ÉTAPE 4 : Transformer en objet JSON imbriqué par année ---

import json

# Grouper par année
grouped_by_year = pivot_df.groupby('annee')

# Créer le dictionnaire final
tableau_1_final = {}

for annee, group_df in grouped_by_year:
    # Retirer la colonne 'annee' (elle devient la clé du dictionnaire)
    liste_arrondissements = group_df.drop(columns='annee').to_dict('records')
    
    # Ajouter au dictionnaire final
    tableau_1_final[annee] = liste_arrondissements

# Afficher en JSON
print("\n--- RÉSULTAT FINAL : Tableau 1 en JSON ---")
print(json.dumps(tableau_1_final, indent=2))

--- RÉSULTAT FINAL : Tableau 1 en JSON ---
{
  "2021": [
    {
      "arrondissement": 1,
      "logements_prives": 289.0,
      "logements_prives_renoves": 112.0,
      "pourcentage_prives_renoves": 38.8,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 289.0,
      "total_logements_renoves": 112.0,
      "pourcentage_total_renove": 38.8
    },
    {
      "arrondissement": 2,
      "logements_prives": 400.0,
      "logements_prives_renoves": 189.0,
      "pourcentage_prives_renoves": 47.2,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 400.0,
      "total_logements_renoves": 189.0,
      "pourcentage_total_renove": 47.2
    },
    {
      "arrondissement": 3,
      "logements_prives": 548.0,
      "logements_prives_renoves": 252.0,
      "pourcentage_prives_renoves": 46.0,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 548.0,
      "total_logements_renoves": 252.0,
      "pourcentage_total_renove": 46.0
    },
    {
      "arrondissement": 4,
      "logements_prives": 618.0,
      "logements_prives_renoves": 349.0,
      "pourcentage_prives_renoves": 56.5,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 618.0,
      "total_logements_renoves": 349.0,
      "pourcentage_total_renove": 56.5
    },
    {
      "arrondissement": 5,
      "logements_prives": 830.0,
      "logements_prives_renoves": 306.0,
      "pourcentage_prives_renoves": 36.9,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 830.0,
      "total_logements_renoves": 306.0,
      "pourcentage_total_renove": 36.9
    },
    {
      "arrondissement": 6,
      "logements_prives": 753.0,
      "logements_prives_renoves": 259.0,
      "pourcentage_prives_renoves": 34.4,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 753.0,
      "total_logements_renoves": 259.0,
      "pourcentage_total_renove": 34.4
    },
    {
      "arrondissement": 7,
      "logements_prives": 788.0,
      "logements_prives_renoves": 306.0,
      "pourcentage_prives_renoves": 38.8,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 788.0,
      "total_logements_renoves": 306.0,
      "pourcentage_total_renove": 38.8
    },
    {
      "arrondissement": 8,
      "logements_prives": 637.0,
      "logements_prives_renoves": 235.0,
      "pourcentage_prives_renoves": 36.9,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 637.0,
      "total_logements_renoves": 235.0,
      "pourcentage_total_renove": 36.9
    },
    {
      "arrondissement": 9,
      "logements_prives": 917.0,
      "logements_prives_renoves": 401.0,
      "pourcentage_prives_renoves": 43.7,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 917.0,
      "total_logements_renoves": 401.0,
      "pourcentage_total_renove": 43.7
    },
    {
      "arrondissement": 10,
      "logements_prives": 1257.0,
      "logements_prives_renoves": 514.0,
      "pourcentage_prives_renoves": 40.9,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 1257.0,
      "total_logements_renoves": 514.0,
      "pourcentage_total_renove": 40.9
    },
    {
      "arrondissement": 11,
      "logements_prives": 1928.0,
      "logements_prives_renoves": 743.0,
      "pourcentage_prives_renoves": 38.5,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 1928.0,
      "total_logements_renoves": 743.0,
      "pourcentage_total_renove": 38.5
    },
    {
      "arrondissement": 12,
      "logements_prives": 1604.0,
      "logements_prives_renoves": 626.0,
      "pourcentage_prives_renoves": 39.0,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 1604.0,
      "total_logements_renoves": 626.0,
      "pourcentage_total_renove": 39.0
    },
    {
      "arrondissement": 13,
      "logements_prives": 1516.0,
      "logements_prives_renoves": 664.0,
      "pourcentage_prives_renoves": 43.8,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 1516.0,
      "total_logements_renoves": 664.0,
      "pourcentage_total_renove": 43.8
    },
    {
      "arrondissement": 14,
      "logements_prives": 1430.0,
      "logements_prives_renoves": 481.0,
      "pourcentage_prives_renoves": 33.6,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 1430.0,
      "total_logements_renoves": 481.0,
      "pourcentage_total_renove": 33.6
    },
    {
      "arrondissement": 15,
      "logements_prives": 3142.0,
      "logements_prives_renoves": 1087.0,
      "pourcentage_prives_renoves": 34.6,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 3142.0,
      "total_logements_renoves": 1087.0,
      "pourcentage_total_renove": 34.6
    },
    {
      "arrondissement": 16,
      "logements_prives": 1968.0,
      "logements_prives_renoves": 686.0,
      "pourcentage_prives_renoves": 34.9,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 1968.0,
      "total_logements_renoves": 686.0,
      "pourcentage_total_renove": 34.9
    },
    {
      "arrondissement": 17,
      "logements_prives": 2643.0,
      "logements_prives_renoves": 975.0,
      "pourcentage_prives_renoves": 36.9,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 2643.0,
      "total_logements_renoves": 975.0,
      "pourcentage_total_renove": 36.9
    },
    {
      "arrondissement": 18,
      "logements_prives": 2698.0,
      "logements_prives_renoves": 1086.0,
      "pourcentage_prives_renoves": 40.3,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 2698.0,
      "total_logements_renoves": 1086.0,
      "pourcentage_total_renove": 40.3
    },
    {
      "arrondissement": 19,
      "logements_prives": 1516.0,
      "logements_prives_renoves": 763.0,
      "pourcentage_prives_renoves": 50.3,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 1516.0,
      "total_logements_renoves": 763.0,
      "pourcentage_total_renove": 50.3
    },
    {
      "arrondissement": 20,
      "logements_prives": 1719.0,
      "logements_prives_renoves": 638.0,
      "pourcentage_prives_renoves": 37.1,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 1719.0,
      "total_logements_renoves": 638.0,
      "pourcentage_total_renove": 37.1
    }
  ],
  "2022": [
    {
      "arrondissement": 1,
      "logements_prives": 1170.0,
      "logements_prives_renoves": 561.0,
      "pourcentage_prives_renoves": 47.9,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 1170.0,
      "total_logements_renoves": 561.0,
      "pourcentage_total_renove": 47.9
    },
    {
      "arrondissement": 2,
      "logements_prives": 1561.0,
      "logements_prives_renoves": 838.0,
      "pourcentage_prives_renoves": 53.7,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 1561.0,
      "total_logements_renoves": 838.0,
      "pourcentage_total_renove": 53.7
    },
    {
      "arrondissement": 3,
      "logements_prives": 2112.0,
      "logements_prives_renoves": 1032.0,
      "pourcentage_prives_renoves": 48.9,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 2112.0,
      "total_logements_renoves": 1032.0,
      "pourcentage_total_renove": 48.9
    },
    {
      "arrondissement": 4,
      "logements_prives": 1730.0,
      "logements_prives_renoves": 753.0,
      "pourcentage_prives_renoves": 43.5,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 1730.0,
      "total_logements_renoves": 753.0,
      "pourcentage_total_renove": 43.5
    },
    {
      "arrondissement": 5,
      "logements_prives": 2892.0,
      "logements_prives_renoves": 1076.0,
      "pourcentage_prives_renoves": 37.2,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 2892.0,
      "total_logements_renoves": 1076.0,
      "pourcentage_total_renove": 37.2
    },
    {
      "arrondissement": 6,
      "logements_prives": 2625.0,
      "logements_prives_renoves": 1158.0,
      "pourcentage_prives_renoves": 44.1,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 2625.0,
      "total_logements_renoves": 1158.0,
      "pourcentage_total_renove": 44.1
    },
    {
      "arrondissement": 7,
      "logements_prives": 2970.0,
      "logements_prives_renoves": 1260.0,
      "pourcentage_prives_renoves": 42.4,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 2970.0,
      "total_logements_renoves": 1260.0,
      "pourcentage_total_renove": 42.4
    },
    {
      "arrondissement": 8,
      "logements_prives": 2479.0,
      "logements_prives_renoves": 1107.0,
      "pourcentage_prives_renoves": 44.7,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 2479.0,
      "total_logements_renoves": 1107.0,
      "pourcentage_total_renove": 44.7
    },
    {
      "arrondissement": 9,
      "logements_prives": 3091.0,
      "logements_prives_renoves": 1306.0,
      "pourcentage_prives_renoves": 42.3,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 3091.0,
      "total_logements_renoves": 1306.0,
      "pourcentage_total_renove": 42.3
    },
    {
      "arrondissement": 10,
      "logements_prives": 4448.0,
      "logements_prives_renoves": 2130.0,
      "pourcentage_prives_renoves": 47.9,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 4448.0,
      "total_logements_renoves": 2130.0,
      "pourcentage_total_renove": 47.9
    },
    {
      "arrondissement": 11,
      "logements_prives": 7576.0,
      "logements_prives_renoves": 3524.0,
      "pourcentage_prives_renoves": 46.5,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 7576.0,
      "total_logements_renoves": 3524.0,
      "pourcentage_total_renove": 46.5
    },
    {
      "arrondissement": 12,
      "logements_prives": 5869.0,
      "logements_prives_renoves": 2816.0,
      "pourcentage_prives_renoves": 48.0,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 5869.0,
      "total_logements_renoves": 2816.0,
      "pourcentage_total_renove": 48.0
    },
    {
      "arrondissement": 13,
      "logements_prives": 5459.0,
      "logements_prives_renoves": 2661.0,
      "pourcentage_prives_renoves": 48.7,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 5459.0,
      "total_logements_renoves": 2661.0,
      "pourcentage_total_renove": 48.7
    },
    {
      "arrondissement": 14,
      "logements_prives": 5417.0,
      "logements_prives_renoves": 2140.0,
      "pourcentage_prives_renoves": 39.5,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 5417.0,
      "total_logements_renoves": 2140.0,
      "pourcentage_total_renove": 39.5
    },
    {
      "arrondissement": 15,
      "logements_prives": 12146.0,
      "logements_prives_renoves": 5255.0,
      "pourcentage_prives_renoves": 43.3,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 12146.0,
      "total_logements_renoves": 5255.0,
      "pourcentage_total_renove": 43.3
    },
    {
      "arrondissement": 16,
      "logements_prives": 8463.0,
      "logements_prives_renoves": 3780.0,
      "pourcentage_prives_renoves": 44.7,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 8463.0,
      "total_logements_renoves": 3780.0,
      "pourcentage_total_renove": 44.7
    },
    {
      "arrondissement": 17,
      "logements_prives": 8864.0,
      "logements_prives_renoves": 3586.0,
      "pourcentage_prives_renoves": 40.5,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 8864.0,
      "total_logements_renoves": 3586.0,
      "pourcentage_total_renove": 40.5
    },
    {
      "arrondissement": 18,
      "logements_prives": 9357.0,
      "logements_prives_renoves": 3770.0,
      "pourcentage_prives_renoves": 40.3,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 9357.0,
      "total_logements_renoves": 3770.0,
      "pourcentage_total_renove": 40.3
    },
    {
      "arrondissement": 19,
      "logements_prives": 6141.0,
      "logements_prives_renoves": 3494.0,
      "pourcentage_prives_renoves": 56.9,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 6141.0,
      "total_logements_renoves": 3494.0,
      "pourcentage_total_renove": 56.9
    },
    {
      "arrondissement": 20,
      "logements_prives": 6480.0,
      "logements_prives_renoves": 3136.0,
      "pourcentage_prives_renoves": 48.4,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 6480.0,
      "total_logements_renoves": 3136.0,
      "pourcentage_total_renove": 48.4
    }
  ],
  "2023": [
    {
      "arrondissement": 1,
      "logements_prives": 1731.0,
      "logements_prives_renoves": 630.0,
      "pourcentage_prives_renoves": 36.4,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 1731.0,
      "total_logements_renoves": 630.0,
      "pourcentage_total_renove": 36.4
    },
    {
      "arrondissement": 2,
      "logements_prives": 2125.0,
      "logements_prives_renoves": 950.0,
      "pourcentage_prives_renoves": 44.7,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 2125.0,
      "total_logements_renoves": 950.0,
      "pourcentage_total_renove": 44.7
    },
    {
      "arrondissement": 3,
      "logements_prives": 3378.0,
      "logements_prives_renoves": 1207.0,
      "pourcentage_prives_renoves": 35.7,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 3378.0,
      "total_logements_renoves": 1207.0,
      "pourcentage_total_renove": 35.7
    },
    {
      "arrondissement": 4,
      "logements_prives": 2609.0,
      "logements_prives_renoves": 943.0,
      "pourcentage_prives_renoves": 36.1,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 2609.0,
      "total_logements_renoves": 943.0,
      "pourcentage_total_renove": 36.1
    },
    {
      "arrondissement": 5,
      "logements_prives": 4687.0,
      "logements_prives_renoves": 1680.0,
      "pourcentage_prives_renoves": 35.8,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 4687.0,
      "total_logements_renoves": 1680.0,
      "pourcentage_total_renove": 35.8
    },
    {
      "arrondissement": 6,
      "logements_prives": 4096.0,
      "logements_prives_renoves": 1693.0,
      "pourcentage_prives_renoves": 41.3,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 4096.0,
      "total_logements_renoves": 1693.0,
      "pourcentage_total_renove": 41.3
    },
    {
      "arrondissement": 7,
      "logements_prives": 5045.0,
      "logements_prives_renoves": 2058.0,
      "pourcentage_prives_renoves": 40.8,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 5045.0,
      "total_logements_renoves": 2058.0,
      "pourcentage_total_renove": 40.8
    },
    {
      "arrondissement": 8,
      "logements_prives": 4004.0,
      "logements_prives_renoves": 1546.0,
      "pourcentage_prives_renoves": 38.6,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 4004.0,
      "total_logements_renoves": 1546.0,
      "pourcentage_total_renove": 38.6
    },
    {
      "arrondissement": 9,
      "logements_prives": 5075.0,
      "logements_prives_renoves": 1982.0,
      "pourcentage_prives_renoves": 39.1,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 5075.0,
      "total_logements_renoves": 1982.0,
      "pourcentage_total_renove": 39.1
    },
    {
      "arrondissement": 10,
      "logements_prives": 7042.0,
      "logements_prives_renoves": 3222.0,
      "pourcentage_prives_renoves": 45.8,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 7042.0,
      "total_logements_renoves": 3222.0,
      "pourcentage_total_renove": 45.8
    },
    {
      "arrondissement": 11,
      "logements_prives": 12121.0,
      "logements_prives_renoves": 5159.0,
      "pourcentage_prives_renoves": 42.6,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 12121.0,
      "total_logements_renoves": 5159.0,
      "pourcentage_total_renove": 42.6
    },
    {
      "arrondissement": 12,
      "logements_prives": 12601.0,
      "logements_prives_renoves": 5676.0,
      "pourcentage_prives_renoves": 45.0,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 12601.0,
      "total_logements_renoves": 5676.0,
      "pourcentage_total_renove": 45.0
    },
    {
      "arrondissement": 13,
      "logements_prives": 14687.0,
      "logements_prives_renoves": 9166.0,
      "pourcentage_prives_renoves": 62.4,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 14687.0,
      "total_logements_renoves": 9166.0,
      "pourcentage_total_renove": 62.4
    },
    {
      "arrondissement": 14,
      "logements_prives": 12588.0,
      "logements_prives_renoves": 6331.0,
      "pourcentage_prives_renoves": 50.3,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 12588.0,
      "total_logements_renoves": 6331.0,
      "pourcentage_total_renove": 50.3
    },
    {
      "arrondissement": 15,
      "logements_prives": 20910.0,
      "logements_prives_renoves": 11444.0,
      "pourcentage_prives_renoves": 54.7,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 20910.0,
      "total_logements_renoves": 11444.0,
      "pourcentage_total_renove": 54.7
    },
    {
      "arrondissement": 16,
      "logements_prives": 11809.0,
      "logements_prives_renoves": 4417.0,
      "pourcentage_prives_renoves": 37.4,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 11809.0,
      "total_logements_renoves": 4417.0,
      "pourcentage_total_renove": 37.4
    },
    {
      "arrondissement": 17,
      "logements_prives": 13888.0,
      "logements_prives_renoves": 5036.0,
      "pourcentage_prives_renoves": 36.3,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 13888.0,
      "total_logements_renoves": 5036.0,
      "pourcentage_total_renove": 36.3
    },
    {
      "arrondissement": 18,
      "logements_prives": 14628.0,
      "logements_prives_renoves": 6864.0,
      "pourcentage_prives_renoves": 46.9,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 14628.0,
      "total_logements_renoves": 6864.0,
      "pourcentage_total_renove": 46.9
    },
    {
      "arrondissement": 19,
      "logements_prives": 15531.0,
      "logements_prives_renoves": 10586.0,
      "pourcentage_prives_renoves": 68.2,
      "logements_sociaux": 0,
      "logements_sociaux_renoves": 0,
      "total_logements": 15531.0,

:

In [61]:
# 1. On pivote
pivot_df = grouped_data.pivot(
    index=['annee', 'arrondissement'],      
    columns='statut_juridique',              
    values=['total_logements', 'total_logements_renove', 'pourcentage_renove']
).reset_index()

# 2. On aplatit les noms des colonnes
pivot_df.columns = [f'{col[0]}_{col[1]}'.lower() if col[1] else col[0] 
                    for col in pivot_df.columns.values]

# 3. ON RENOMME (Attention aux noms exacts générés par l'étape précédente)
# Note : Si votre statut juridique est "Privé (individuel)", 
# après le .lower() au dessus, la colonne s'appelle "total_logements_privé (individuel)"
pivot_df = pivot_df.rename(columns={
    'total_logements_privé (individuel)': 'logements_prives',
    'total_logements_social': 'logements_sociaux',
    'total_logements_renove_privé (individuel)': 'logements_prives_renoves',
    'total_logements_renove_social': 'logements_sociaux_renoves',
    'pourcentage_renove_privé (individuel)': 'pourcentage_prives_renoves', # Correction de la guillemet en trop ici
    'pourcentage_renove_social': 'pourcentage_sociaux_renoves'
})

# 4. On remplace les cases vides (NaN) par 0
pivot_df = pivot_df.fillna(0)

# 5. On termine les calculs totaux
pivot_df['total_logements'] = pivot_df['logements_prives'] + pivot_df['logements_sociaux']
pivot_df['total_logements_renoves'] = pivot_df['logements_prives_renoves'] + pivot_df['logements_sociaux_renoves']

# Pourcentage global (privé + social)
pivot_df['pourcentage_total_renove'] = ((pivot_df['total_logements_renoves'] / pivot_df['total_logements']).fillna(0) * 100).round(1)

print(pivot_df)

KeyError: 'logements_sociaux'

In [ ]:
# 2. Grouper et compter
result_df = df_light.groupby(['annee', 'arrondissement']).agg({
    'is_renovated': ['count', 'mean'],
    'total': ['count']
}).reset_index()
# 3. Renommer les colonnes
result_df.columns = ['annee', 'arrondissement','total_logements_renove' , 'pourcentage_renove','total_logements']
result_df['pourcentage_renove'] = (result_df['pourcentage_renove'] * 100).round(2)
result_df

KeyError: "Column(s) ['total'] do not exist"

In [9]:
renovation_pivot = renovation_by_postal_and_status_df.unstack(fill_value=0).round(2)
renovation_pivot

statut_juridique  Privé (Copro)  Privé (Individuel)  Social
année
2021                      30.48               39.72    0.00
2022                      35.46               45.27    0.00
2023                      28.52               49.14    0.00
2024                      29.05               56.09    0.00
2025                      27.58               48.86   11.36
2026                      38.22               47.55    0.00

In [10]:
for column in renovation_pivot.columns:
    if column == "Social":
        df_light["pourcentage_renover_social"] = df_light["code_postal_brut"].map(
            renovation_pivot["Social"]
        )
    elif column == "Privé (Copro)":
        df_light["pourcentage_renover_privet_copro"] = df_light["code_postal_brut"].map(
            renovation_pivot["Privé (Copro)"]
        )

    df_light["pourcentage_renover_privet_individuel"] = df_light[
        "code_postal_brut"
    ].map(renovation_pivot["Privé (Individuel)"])

df_light.drop(columns='is_renovated')

,numero_dpe,date_etablissement_dpe,date_fin_validite_dpe,numero_rpls_logement,numero_immatriculation_copropriete,etiquette_dpe,etiquette_ges,type_batiment,annee_construction,nombre_appartement,...,type_energie_principale_chauffage,type_ventilation,statut_juridique,année,code_postal_clean,arrondissement,total,pourcentage_renover_privet_copro,pourcentage_renover_privet_individuel,pourcentage_renover_social
0,2675E0081184O,2026-01-12,2036-01-11,NaN,NaN,F,C,appartement,NaN,1.0,...,Électricité,NaN,Privé (Individuel),2026,75004,4,1,NaN,NaN,NaN
1,2675E0079556Y,2026-01-12,2036-01-11,NaN,NaN,D,D,appartement,NaN,1.0,...,Réseau de Chauffage urbain,NaN,Privé (Individuel),2026,75011,11,1,NaN,NaN,NaN
2,2675E0082260Y,2026-01-12,2036-01-11,NaN,NaN,F,C,appartement,NaN,1.0,...,Électricité,NaN,Privé (Individuel),2026,75015,15,1,NaN,NaN,NaN
3,2675E0081107P,2026-01-12,2036-01-11,NaN,NaN,F,C,appartement,1975.0,1.0,...,Électricité,NaN,Privé (Individuel),2026,75017,17,1,NaN,NaN,NaN
4,2675E0077739B,2026-01-12,2036-01-11,NaN,NaN,E,E,appartement,1880.0,NaN,...,Gaz naturel,NaN,Privé (Individuel),2026,75009,9,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750224,2175E0000627A,2021-07-01,2031-06-30,NaN,NaN,F,F,appartement,NaN,1.0,...,Électricité,NaN,Privé (Individuel),2021,75016,16,1,NaN,NaN,NaN
750225,2175E0000375I,2021-07-01,2031-06-30,NaN,NaN,D,B,appartement,NaN,1.0,...,Électricité,NaN,Privé (Individuel),2021,75015,15,1,NaN,NaN,NaN
750226,2175E0001823A,2021-07-01,2031-06-30,NaN,NaN,C,C,appartement,NaN,1.0,...,Électricité,NaN,Privé (Individuel),2021,75009,9,1,NaN,NaN,NaN
750227,2175E1044675S,2021-07-01,2031-06-30,NaN,NaN,E,E,appartement,1974.0,1.0,...,Gaz naturel,NaN,Privé (Individuel),2021,75015,15,1,NaN,NaN,NaN
750228,2175E1043000H,2021-07-01,2031-06-30,NaN,NaN,E,C,appartement,1949.0,NaN,...,Électricité,NaN,Privé (Individuel),2021,75010,10,1,NaN,NaN,NaN

In [11]:
import pandas as pd
import json
import os

class TableFactory:
    def __init__(self, df_light, config_json_path):
        """
        Au moment de la construction, on reçoit le DataFrame nettoyé
        et le chemin vers la configuration des colonnes.
        """
        self.df = df_light
        with open(config_json_path, 'r', encoding='utf-8') as f:
            self.config = json.load(f)
        
        # Ce dictionnaire stockera les DataFrames générés
        self.generated_tables = {}

    def _generate_single_table(self, table_name):
        """
        MÉTHODE PRIVÉE : Fabrique une table à partir du nom dans le JSON.
        """
        if table_name not in self.config:
            print(f"⚠️ La table '{table_name}' n'est pas dans le fichier config.")
            return None
        
        cols = self.config[table_name]
        print(f"🔨 Génération de {table_name}...")
        return self.df[cols].copy()

    def generate_all(self):
        """
        Boucle sur le JSON pour fabriquer toutes les tables d'un coup.
        """
        for table_name in self.config.keys():
            self.generated_tables[table_name] = self._generate_single_table(table_name)

    def export_to_json(self, output_dir):
        """
        Exporte les tables générées en fichiers JSON pour le Front-end.
        """
        os.makedirs(output_dir, exist_ok=True)
        
        for name, df in self.generated_tables.items():
            path = os.path.join(output_dir, f"{name}.json")
            df.to_json(path, orient='records', force_ascii=False, indent=2)
            print(f"✅ Exporté : {path}")

    def get_json_payload(self):
        """
        Au lieu de sauvegarder des fichiers, cette méthode retourne 
        directement les données au format JSON pour un Contrôleur API.
        """
        payload = {}
        for name, df in self.generated_tables.items():
            # On transforme le DF en dictionnaire Python (format JSON compatible)
            payload[name] = df.to_dict(orient='records')
        return payload

In [12]:
f=TableFactory()

TypeError: TableFactory.__init__() missing 2 required positional arguments: 'df_light' and 'config_json_path'